<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>astrocli</AssemblyName>
    <RootNamespace>AstroCli</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CosineKitty.AstronomyEngine" Version="2.1.19" />
    <PackageReference Include="SharpAstrology.SwissEph" Version="0.4.2" />
  </ItemGroup>

</Project>
