namespace AstroCli;

public static class SabianSymbols
{
    // Jones-version Sabian symbol source phrases, scraped from James Burgess sign list pages.
    // Source index page: https://www.jamesburgess.com/sabian-symbols.html
    private static readonly string[] Symbols =
    [
        "A woman rises out of the water, a seal rises and embraces her",
        "A comedian entertaining a group.",
        "A cameo profile of a man, in the outline of his country",
        "Two lovers strolling through a secluded walk",
        "A triangle with wings",
        "A square brightly lighted on one side.",
        "A man successfully expressing himself in two realms at once.",
        "A large hat with streamers flying, facing east.",
        "A crystal gazer.",
        "A man teaching new forms for old symbols.",
        "The president of the country",
        "A flock of wild geese.",
        "An unsuccessful bomb explosion.",
        "A serpent coiling near a man and a woman.",
        "An Indian weaving a blanket.",
        "Brownies dancing in the setting sun.",
        "Two prim spinsters",
        "An empty hammock.",
        "The magic carpet.",
        "A young girl feeding birds in winter.",
        "A pugilist entering the ring.",
        "The gate to the garden of desire.",
        "Woman in pastels carrying a heavy and valuable but veiled load.",
        "An open window and a net curtain blowing into a cornucopia.",
        "A double promise",
        "A man possessed of more gifts than he can hold.",
        "A lost opportunity is regained in the imagination.",
        "A large disappointed audience.",
        "A celestial choir singing.",
        "A duck pond and its brood.",
        "A clear mountain stream.",
        "An electrical storm.",
        "Steps up to a lawn blooming with clover.",
        "The rainbow's pot of gold.",
        "A widow at an open grave.",
        "A bridge being built across a gorge.",
        "A woman of Samaria.",
        "A sleigh without snow.",
        "A Christmas tree decorated.",
        "A Red Cross nurse.",
        "A woman sprinkling flowers.",
        "Window shoppers.",
        "A man handling baggage.",
        "Shellfish groping and children playing",
        "A man muffled up with a rakish silk hat",
        "An old man vainly attempting to reveal the Mysteries.",
        "A battle between the swords and the torches.",
        "A woman holding a bag out of a window.",
        "A newly formed continent.",
        "Wind, clouds and haste.",
        "A finger pointing in an open book.",
        "White dove over troubled waters.",
        "A jewellery shop",
        "A mounted Indian with scalp locks.",
        "A large well-kept public park.",
        "A Spaniard serenading his senorita.",
        "An old Indian woman selling beads.",
        "A mature woman reawakened to romance.",
        "Two cobblers working at a table.",
        "A peacock parading on an ancient lawn.",
        "A glass-bottomed boat in still water.",
        "Santa Claus filling stockings furtively.",
        "The garden of the Tuileries.",
        "Holly and mistletoe.",
        "A radical magazine",
        "Drilling for oil.",
        "An old-fashioned well.",
        "An industrial strike.",
        "A quiver filled with arrows.",
        "An airplane falling.",
        "A new path of realism in experience.",
        "A Topsy saucily asserting herself",
        "A great musician at his piano.1",
        "A conversation by telepathy",
        "Two Dutch children talking.",
        "A woman suffragist haranguing.",
        "The head of health dissolved into the head of mentality.",
        "Two Chinese men talking Chinese.",
        "A large archaic volume",
        "A cafeteria",
        "A labour demonstration.",
        "A barn dance",
        "Three fledglings in a nest high in a tree.",
        "Children skating on ice.",
        "A man trimming palms.",
        "Winter frost in the woods.",
        "A gypsy coming out of the forest.",
        "A man declared bankrupt.",
        "The first mockingbird in spring",
        "Bathing beauties.",
        "A furled and unfurled flag displayed from a vessel.",
        "A man suspended over a vast level place",
        "A man all bundled up in fur leading a shaggy deer.",
        "A cat arguing with a mouse.",
        "An automobile is wrecked by a train.",
        "Game birds feathering their nests.",
        "Two fairies on a moonlit night.",
        "Rabbits dressed in clothes and on parade.",
        "A tiny, nude miss reaching in the water for a fish.",
        "A large diamond not completely cut.",
        "A clown making grimaces.",
        "Chinese woman nursing a baby with a message.",
        "One hand slightly flexed with a very prominent thumb.",
        "A very old man facing a vast dark space to the northeast.",
        "A group of people who have overeaten and enjoyed it.",
        "A man before a square with a manuscript roll before him.",
        "The germ grows into knowledge and life.",
        "A hen scratching for her chicks.",
        "A priest performing a marriage ceremony.",
        "Gondoliers in a serenade.",
        "A Prima Donna singing.",
        "A woman awaiting a sailboat.",
        "The meeting of a literary society.",
        "A woman and two men on a bit of sunlit land facing South.",
        "Dark shadow or mantle thrown suddenly over the right shoulder",
        "Contentment and happiness, people reading on davenports",
        "A storm in a canyon.",
        "A modern Pocahontas.",
        "A muse weighing twins.",
        "A Daughter of the American Revolution.",
        "A case of apoplexy.",
        "An epidemic of mumps",
        "A woman, having her hair bobbed.",
        "Man formally dressed and a deer with its horns folded.",
        "Rock formations at the edge of a precipice.",
        "Old fashioned woman is confronted by an up-to-date girl.",
        "The constellations in the sky.",
        "A Bolshevik propagandist.",
        "Glass blowers",
        "Early morning dew.",
        "Children on a swing in a huge oak tree.",
        "An evening lawn party",
        "An old sea captain.",
        "The human soul awaiting opportunity for expression.",
        "A pageant.",
        "Sunshine just after a storm.",
        "A non-vested church choir",
        "A teacher of chemistry.",
        "A houseboat party.",
        "The Zuni sun worshippers.",
        "Intoxicated chickens.",
        "A carrier pigeon.",
        "A bareback rider.",
        "An untidy, unkempt man.",
        "A large camel crossing the desert.",
        "A rainbow.",
        "Daybreak",
        "Many little birds on the limb of a large tree.",
        "A mermaid.",
        "An unsealed letter.",
        "A man's head.",
        "A large white cross upraised.",
        "Two angels bringing protection.",
        "A child of colour playing with white children.",
        "A man dreaming of fairies.",
        "A merry-go-round.",
        "A harem.",
        "First dancing instruction.",
        "A man makes a futuristic drawing.",
        "Two heads looking out and beyond the shadows.",
        "A boy moulded in his mother's aspirations for him.",
        "A bride with her veil snatched away.",
        "A strong hand supplanting political hysteria.",
        "A family tree.",
        "An ornamental handkerchief.",
        "An orangutan.",
        "A volcanic in eruption.",
        "A Ouija board.",
        "A swimming race.",
        "An automobile caravan.",
        "A girls’ basketball team.",
        "A royal coat of arms.",
        "An animal trainer.",
        "Mary and her white lamb.",
        "A flag at half-mast.",
        "A boy with a censer.",
        "Grandes Dames at tea.",
        "A bald-headed man.",
        "A man gaining secret knowledge from a paper he is reading.",
        "A false call unheard in attention to immediate service.",
        "A butterfly made perfect by a dart through it.",
        "The light of the sixth race transmuted to the seventh.",
        "The dawn of a new day, everything changed.",
        "A group around a campfire.",
        "A man teaching the true inner knowledge.",
        "The ideals of a man abundantly crystallised.",
        "A woman feeding chickens and protecting them from the hawks.",
        "A blazing fireplace in a deserted home.",
        "Three old masters hanging in an art gallery.",
        "A canoe approaching safety through dangerous waters.",
        "A professor peering over his glasses.",
        "Miners are emerging from a mine.",
        "Children blowing soap bubbles.",
        "A noon siesta.",
        "Circular paths.",
        "A boat landing washed away",
        "A retired sea captain.",
        "Two men placed under arrest.",
        "A gang of robbers in hiding.",
        "A Jewish rabbi.",
        "A crowd upon the beach.",
        "A child giving birds a drink at a fountain.",
        "Chanticleer.",
        "A third wing on the left side of a butterfly.",
        "Information in the symbol of an autumn leaf",
        "An eagle and a large white dove turning one into the other.",
        "An airplane hovering overhead.",
        "A man in the midst of brightening influences.",
        "Humanity seeking to bridge the span of knowledge.",
        "Three mounds of knowledge on a philosopher's head.",
        "A sight-seeing bus.",
        "A broken bottle and spilled perfume.",
        "A house-raising.",
        "A youth holding a lighted candle.",
        "A massive, rocky shore.",
        "A gold rush.",
        "Deep-sea divers.",
        "The moon shining across a lake.",
        "Dental work.",
        "A fellowship supper.",
        "A drowning man rescued.",
        "An embassy ball.",
        "An inventor experimenting.",
        "Telephone linemen at work.",
        "Children playing around five mounds of sand.",
        "A girl's face breaking into a smile.",
        "A woman, the father of her own child",
        "A woods rich in autumn colouring.",
        "A parrot listening and then talking.",
        "Woman drawing two dark curtains aside.",
        "A soldier derelict in his duty.",
        "Hunters starting out for ducks.",
        "A rabbit metamorphosed into a fairy",
        "Crowds coming down the mountain to listen to one man.",
        "An x ray .",
        "Indians making camp",
        "A military band on the march.",
        "The king of the fairies approaching his domain.",
        "Indian woman pleading to the chief for the lives of her children.",
        "The Halloween jester.",
        "A Grand Army of the Republic campfire.",
        "The ocean covered with whitecaps.",
        "Two men playing chess.",
        "A little child learning to walk.",
        "An old owl up in a tree.",
        "A game of cricket.",
        "Cupid knocking at the door",
        "Rocks and things forming therein.",
        "A mother with her children on the stairs.",
        "A golden haired 'goddess of opportunity'.",
        "The lamp of physical enlightenment at the left temple.",
        "A flag that turns into an eagle that crows.",
        "A widow's past is brought to light.",
        "The Pyramids and the Sphinx.",
        "The ground hog looking for its shadow",
        "Seagulls watching a ship.",
        "An Easter sunrise service.",
        "Tiny children in sunbonnets.",
        "Pelicans moving their habitat.",
        "Men cutting through ice",
        "A child and a dog with borrowed eyeglasses.",
        "A Chinese laundry.",
        "Immigrants entering.",
        "A bluebird standing at the door of the house.",
        "A chubby boy on a hobbyhorse.",
        "A flag-bearer.",
        "A sculptor",
        "An old bridge over a beautiful stream",
        "A fat boy mowing the lawn.",
        "The Pope",
        "An Indian chief demanding recognition.",
        "Three stained-glass windows, one damaged by bombardment.",
        "The human soul receptive to growth and understanding.",
        "A party entering a large canoe.",
        "Indians rowing a canoe and dancing a war dance.",
        "A dark archway and ten logs at the bottom.",
        "A veiled prophet of power",
        "Birds in the house singing happily.",
        "An angel carrying a harp.",
        "An albatross feeding from the hand.",
        "A large group of pheasants",
        "A student of nature lecturing.",
        "A fire worshipper.",
        "Ancient bas-relief carved in granite.",
        "Many toys in the children's ward of a hospital.",
        "Boys and girls in gymnasium suits.",
        "A girl surreptitiously bathing in the nude.",
        "The Union Jack.",
        "A child of about five carrying a huge shopping bag.",
        "A hidden choir singing.",
        "A relay race.",
        "A general accepting defeat gracefully.",
        "Two awards for bravery in war.",
        "A woman entering a convent.",
        "An oriental rug dealer",
        "A water sprite.",
        "A mountain pilgrimage.",
        "A large aviary.",
        "A woman reading tea leaves.",
        "A secret business conference.",
        "An old adobe mission.",
        "An unexpected thunderstorm.",
        "A deserter from the navy.",
        "A Hindu healer.",
        "A council of ancestors.",
        "A performer of a mystery play.",
        "A child born of an eggshell.",
        "Beautifully gowned wax figures.",
        "A flag turned into an eagle.",
        "A popularity that proves ephemeral.",
        "Man tête-à-tête with his inspiration.",
        "People on stairs graduated upwards.",
        "A barometer.",
        "A train entering a tunnel.",
        "Two lovebirds sitting on a fence.",
        "A big-businessman at his desk.",
        "A watchdog standing guard.",
        "A man unmasked.",
        "A forest fire quenched.",
        "A big white dove, a message bearer.",
        "Woman disappointed, disillusioned.",
        "A rug placed on a floor for children to play.",
        "A big bear sitting down and waving all its paws.",
        "Man turning his back on his passions teaches from his experience.",
        "A butterfly with the right wing more perfectly formed.",
        "A hydrometer.",
        "An ancient pottery bowl filled with fresh violets.",
        "A tree felled and sawed.",
        "Butterfly emerging from a chrysalis.",
        "The field of Ardath in bloom.",
        "A public market.",
        "A squirrel hiding from hunters.",
        "A petrified forest.",
        "Heavy car traffic on a narrow isthmus.",
        "A church bazaar.",
        "Officers on dress parade.",
        "A cross lying on the rocks.",
        "A girl blowing a bugle.",
        "A jockey",
        "An aviator in the clouds.",
        "Men seeking illumination.",
        "An examination of initiates.",
        "A sword in a museum.",
        "A lady in fox fur.",
        "An officer preparing to drill his men.",
        "The flow of inspiration.",
        "An Easter promenade.",
        "A gigantic tent.",
        "A master instructing his pupil.",
        "A table set for an evening meal.",
        "A little white lamb, a child and a Chinese servant.",
        "A man bringing down the new law from Sinai.",
        "Spiritist phenomena.",
        "An inhabited island.",
        "The purging of the priesthood.",
        "A new moon that divides its influences.",
        "A harvest moon.",
        "A fertile garden under the full moon.",
        "A prism.",
        "The Great Stone Face"
    ];

    public static string SymbolForIndex(int index)
    {
        if (index < 1 || index > Symbols.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(index), "Sabian index must be in the range [1, 360].");
        }

        return Symbols[index - 1];
    }
}
